tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      source "$THEIA_WORKSPACE_ROOT/bin/ecr/login"
  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev   
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source  "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"
      source  "$THEIA_WORKSPACE_ROOT/bin/services/start"
      
  - name: react-js
    command: |
      cd frontend-react-js
      npm update -g
      npm i
      cd $THEIA_WORKSPACE_ROOT
  - name: flask 
    command: |
      cd backend-flask
      pip install -r requirements.txt
  - name: fargate session manager
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      session-manager-plugin
      cd backend-flask
      

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    
# open the ports for the service by default
ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
